language: python

notifications:
  email: false


matrix:
  include:
    - os: linux
      python: "2.7"
      # Tell travis we want debian trusty
      sudo: required
      dist: trusty
      env:
        - TESTATTR="'not huge and not known_failing'"
      addons:
        apt:
          packages:
            - astyle
            - cppcheck
            - enchant

    - os: osx
      language: generic
      osx_image: xcode7.3
      env:
        - TESTATTR="'not linux and not known_failing and not huge'"
      before_install:
        - source ci_scripts/install.sh

# command to install common dependencies
install:
  - python --version
  - which python
  - gcc --version
  - which gcc
  - make install-dependencies

# command to run tests
script:
  - make test

# generate all the diagnostic reports
after_success:
  - PYTEST_ADDOPTS=-qqq make coverage-gcovr.xml coverage.xml
  # Fix suggested by http://diff-cover.readthedocs.io/en/latest/#troubleshooting
  - git fetch origin master:refs/remotes/origin/master
  - PYTEST_ADDOPTS=-qqq make diff-cover
  - make format
  - make diff_pylint_report
  - make cppcheck
  - make pydocstyle
  # do the docs build?
  - make doc
  # XXX Do not upload results from travis yet. Currently jenkins is considered
  # XXX the source of truth about coverage
  # only upload the linux coverage report to codecov as it merges all reports
  # from all builds into one
  #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip install codecov; fi
  #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then codecov -X pycov search gcov -f coverage.xml coverage-gcovr.xml; fi
